### ISSUE TITLE
cannot import name '_C' from 'model'(/RFA-Net-master/RFA-Net-master/lib/model/__init__.py)

### ISSUE THREAD

**Issue by HarryKang13** [ygzhu/RFA-Net#1]
祝博士您好，请教一个RFA-Net代码中的问题：model/__init__.py文件为空，导入._C失败，但好多文件中都用到了这个._C，请教您该如何解决。

**Comment by ygzhu** [comment]
> 祝博士您好，请教一个RFA-Net代码中的问题：model/**init**.py文件为空，导入._C失败，但好多文件中都用到了这个._C，请教您该如何解决。

https://github.com/jwyang/faster-rcnn.pytorch/issues/503#issuecomment-483561747
